variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - test
  - deploy
  - docs
  - build-pack
  - test-pack

##############################################
# Общие этапы подготовки (только для astra)
##############################################
ensure-submodule:
  stage: prepare
  script:
    - if [ ! -d "googletest" ]; then
      git submodule add https://github.com/google/googletest.git googletest;
      fi
    - git submodule update --init --recursive
    - ls -la
    - ls -la googletest || true
  artifacts:
    paths:
      - googletest/
    expire_in: 1 week
  tags:
    - astra  # Только для astra

build-gtest:
  stage: prepare
  needs: ["ensure-submodule"]
  script:
    - cd googletest
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4
    - ls -la lib/
  artifacts:
    paths:
      - googletest/build/lib/
    expire_in: 1 week
  tags:
    - astra  # Только для astra

##############################################
# RED OS подготовка (отдельный этап)
##############################################
prepare-redos:
  stage: prepare
  script:
    - git submodule update --init --recursive
    - cd googletest
    - mkdir -p build && cd build
    - cmake ..
    - make -j4
  artifacts:
    paths:
      - googletest/build/lib/
    expire_in: 1 week
  tags:
    - redos  # Только для redos

##############################################
# Сборка проекта
##############################################
astra-build:
  stage: build
  needs: ["build-gtest"]
  before_script:
    - apt-get update -qq
    - apt-get install -y build-essential g++
  script:
    - make all
  artifacts:
    paths:
      - ./calc
      - ./test
      - ./leak_test
    expire_in: 1 week
  tags:
    - astra

redos-build:
  stage: build
  needs: ["prepare-redos"]
  before_script:
    - dnf install -y gcc-c++ make
  script:
    - make all
  artifacts:
    paths:
      - ./calc
      - ./test
      - ./leak_test
    expire_in: 1 week
  tags:
    - redos

##############################################
# Тестирование (Astra)
##############################################
astra-unit-test:
  stage: test
  needs: ["astra-build"]
  script:
    - ./test --gtest_output="xml:report.xml"
  artifacts:
    reports:
      junit: report.xml
  tags:
    - astra

astra-leak-test:
  stage: test
  dependencies:
    - astra-build
  needs: ["astra-build"]
  script:
    - ./leak_test
  tags:
    - astra

astra-deploy:
  stage: deploy
  dependencies:
    - astra-build
  needs:
    - job: 'astra-build'
    - job: 'astra-leak-test'
    - job: 'astra-unit-test'
  script:
    - ./calc
  artifacts:
    name: "astra-deploy-result"
    paths:
      - ./calc
  tags:
    - astra

astra-package:
  stage: build-pack
  dependencies:
    - astra-deploy
  needs: ["astra-deploy"]
  script:
    - mv ./calc calculator
    - mkdir calc
    - cd calc
    - mkdir bin
    - mkdir etc
    - mv ../calculator bin/calc
    - mv ../packages/calc.conf etc
    - mkdir DEBIAN
    - mv ../packages/control DEBIAN
    - cd ../
    - dpkg-deb --build calc
  artifacts:
    name: "astra-package-result"
    paths:
      - ./calc.deb
  tags:
    - astra

astra-package-test:
  stage: test-pack
  dependencies:
    - astra-package
  needs: ["astra-package"]
  script:
    - apt install ./calc.deb -y
    - dpkg-query -L calc
    - calc
  tags:
    - astra

redos-unit-test:
  stage: test
  dependencies:
    - redos-build
  needs: ["redos-build"]
  script:
    - ./test --gtest_output="xml:report.xml"
  artifacts:
    when: always
    name: "redos_test_results"
    paths:
      - ./report.xml
  tags:
    - redos

redos-leak-test:
  stage: test
  dependencies:
    - redos-build
  needs: ["redos-build"]
  script:
    - ./leak_test
  tags:
    - redos

redos-deploy:
  stage: deploy
  dependencies:
    - redos-build
  needs:
    - job: 'redos-build'
    - job: 'redos-leak-test'
    - job: 'redos-unit-test'
  script:
    - ./calc
  artifacts:
    name: "redos-deploy-result"
    paths:
      - ./calc
  tags:
    - redos

redos-package:
  stage: build-pack
  dependencies:
    - redos-deploy
  needs: ["redos-deploy"]
  before_script:
    - dnf update -y
    - dnf install -y rpm-build
    - dnf install -y rpmdevtools
  script:
    - echo "Build redos package"
    - rpmdev-setuptree && find /root
    - mkdir calc-1.0.0
    - mv calc calc-1.0.0
    - tar --create --file calc-1.0.0.tar.gz calc-1.0.0
    - mv calc-1.0.0.tar.gz /root/rpmbuild/SOURCES
    - mv packages/calc.spec /root/rpmbuild/SPECS/calc.spec
    - rpmbuild -ba /root/rpmbuild/SPECS/calc.spec
  artifacts:
    name: "redos-package-result"
    paths:
      - ./x86_64/calc-1.0.0-1.el7.x86_64.rpm
  tags:
    - redos

redos-package-test:
  stage: test-pack
  dependencies:
    - redos-package
  needs: ["redos-package"]
  script:
    - dnf install ./x86_64/calc-1.0.0-1.el7.x86_64.rpm -y
    - rpm -ql ./x86_64/calc-1.0.0-1.el7.x86_64.rpm
    - calc
  tags:
    - redos

build-docs:
  stage: docs
  needs:
    - job: 'redos-unit-test'
    - job: 'astra-unit-test'
    - job: 'astra-leak-test'
    - job: 'redos-leak-test'
  before_script:
    - sudo apt-get update
    - sudo apt-get install doxygen -y
  script:
    - doxygen Doxyfile
  artifacts:
    name: "docs"
    paths:
      - ./html
  tags:
    - astra