stages:
  - build
  - test
  - deploy
  - docs
  - build-pack
  - test-pack

astra-build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  script:
    - cd googletest
    - cmake -S . -B build
    - cd build
    - make -j 4
    - cd ../../
    - make all
  artifacts:
    name: "astra_build_result"
    paths:
      - ./calc
      - ./test
      - ./leak_test
    expire_in: 1 week
  tags:
    - astra

astra-unit-test:
  stage: test
  dependencies:
    - astra-build
  needs: ["astra-build"]
  script:
    - ./test --gtest_output="xml:report.xml"
  artifacts:
    when: always
    name: "astra_test_results"
    paths:
      - ./report.xml
  tags:
    - astra

astra-leak-test:
  stage: test
  dependencies:
    - astra-build
  needs: ["astra-build"]
  script:
    - ./leak_test
  tags:
    - astra

astra-deploy:
  stage: deploy
  dependencies:
    - astra-build
  needs:
    - job: 'astra-build'
    - job: 'astra-leak-test'
    - job: 'astra-unit-test'
  script:
    - ./calc
  artifacts:
    name: "astra-deploy-result"
    paths:
      - ./calc
  tags:
    - astra

astra-package:
  stage: build-pack
  dependencies:
    - astra-deploy
  needs: ["astra-deploy"]
  script:
    - mv ./calc calculator
    - mkdir calc
    - cd calc
    - mkdir bin
    - mkdir etc
    - mv ../calculator bin/calc
    - mv ../packages/calc.conf etc
    - mkdir DEBIAN
    - mv ../packages/control DEBIAN
    - cd ../
    - dpkg-deb --build calc
  artifacts:
    name: "astra-package-result"
    paths:
      - ./calc.deb
  tags:
    - astra


astra-package-test:
  stage: test-pack
  dependencies:
    - astra-package
  needs: ["astra-package"]
  script:
    - apt install ./calc.deb -y
    - dpkg-query -L calc
    - calc
  tags:
    - astra

redos-build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  script:
    - cd googletest
    - cmake -S . build
    - cd build
    - make -j 4
    - cd ../../
    - make all
  artifacts:
    name: "redos_build_result"
    paths:
      - ./calc
      - ./test
      - ./leak_test
    expire_in: 1 week
  tags:
    - redos


redos-unit-test:
  stage: test
  dependencies:
    - redos-build
  needs: ["redos-build"]
  script:
    - ./test --gtest_output="xlm:report.xml"
  artifacts:
    when: always
    name: "redos_test_results"
    paths:
      - ./report.xml
  tags:
    - redos

redos-leak-test:
  stage: test
  dependencies:
    - redos-build
  needs: ["redos-build"]
  script:
    - ./leak_test
  tags:
    - redos

redos-deploy:
  stage: deploy
  dependencies:
    - redos-build
  needs:
    - job: 'redos-build'
    - job: 'redos-leak-test'
    - job: 'redos-unit-test'
  script:
    - ./calc
  artifacts:
    name: "redos-deploy-result"
    paths:
      - ./calc
  tags:
    - redos