stages:
  - build
  - test
  - deploy
  - docs
  - build-pack
  - test-pack

astra-build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  script:
    - cd googletest
    - cmake -S . -B build
    - cd build
    - make -j 4
    - cd ../../
    - make all
  artifacts:
    name: "astra_build_result"
    paths:
      - ./calc
      - ./test
      - ./leak_test
    expire_in: 1 week
  tags:
    - astra

astra-unit-test:
  stage: test
  dependencies:
    - astra-build
  needs: [ "astra-build" ]
  script:
    - ./test --gtest_output="xml:report.xml"
  artifacts:
    when: always
    name: "astra_test_results"
    paths:
      - ./report.xml
  tags:
    - astra

astra-leak-test:
  stage: test
  dependencies:
    - astra-build
  needs: [ "astra-build" ]
  script:
    - ./leak_test
  tags:
    - astra

astra-deploy:
  stage: deploy
  dependencies:
    - astra-build
  needs:
    - job: 'astra-build'
    - job: 'astra-leak-test'
    - job: 'astra-unit-test'
  script:
    - ./calc
  artifacts:
    name: "astra-deploy-result"
    paths:
      - ./calc
  tags:
    - astra